### ISSUE TITLE
hwid leak??

### ISSUE THREAD

**Issue by aaesth** [sigmaclientwastaken/windhook-rip#3]
was looking in the code for no reason at all and found the hwid manager with a pastebin to peoples hwid and username

https://github.com/aesth1/skidium/blob/main/Untitled.png?raw=true

**Comment by aaesth** [comment]
idk what you can do with hwids but im just pointing this out

**Comment by aaesth** [comment]
oh btw can you link the libraries to compile the client

**Comment by sigmaclientwastaken** [comment]
> oh btw can you link the libraries to compile the client

discord-rpc is the only library used, i dont know where you can find the jar tho

**Comment by aaesth** [comment]
some com.jhlabs.image library literally cant find it 

dont really need it anymore since i deleted the parts where it uses it

**Comment by sigmaclientwastaken** [comment]
> some com.jhlabs.image library literally cant find it
> 
> dont really need it anymore since i deleted the parts where it uses it

thats useless code, I dont think its used anywhere other than some imports

**Comment by aaesth** [comment]
there were some strings that used it but i dont need it now
